# Generated by Django 4.2.11 on 2025-09-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('Casual', 'Casual Leave'), ('Sick', 'Sick Leave'), ('Jamat', 'Jamat Leave'), ('Earned', 'Earned Leave'), ('Unpaid', 'Unpaid Leave'), ('Other', 'Other')], max_length=20),
        ),
    ]
