# Generated by Django 4.2.11 on 2025-08-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0002_company_alter_attendance_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='device_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='device_port',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
