# Generated by Django 4.2.11 on 2025-08-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0004_employee_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendances'},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['employee', 'timestamp'], name='attendance__employe_df1fee_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['company', 'timestamp'], name='attendance__company_408b4f_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status', 'timestamp'], name='attendance__status_ea62da_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('employee', 'timestamp', 'status'), name='uniq_employee_timestamp_status'),
        ),
    ]
