# Generated by Django 4.2.11 on 2025-08-16 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0005_alter_attendance_options_alter_attendance_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZKDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('secret', models.CharField(blank=True, max_length=64, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance_app.department')),
            ],
        ),
    ]
