# Generated by Django 4.2.11 on 2025-08-16 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0006_zkdevice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZKDevice',
        ),
    ]
