# Generated by Django 4.2.11 on 2025-08-19 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_app', '0002_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
