# Generated by Django 4.2.11 on 2025-09-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_app', '0004_alter_subscriptionplan_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='employee_limit',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
