# Generated by Django 4.2.11 on 2025-08-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeprofile',
            old_name='voter_id',
            new_name='national_id',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='branch_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='employee_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='job_type',
            field=models.CharField(blank=True, choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Contract', 'Contract'), ('Intern', 'Intern')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='joining_letter',
            field=models.FileField(blank=True, null=True, upload_to='employee_docs/'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='offer_letter',
            field=models.FileField(blank=True, null=True, upload_to='employee_docs/'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='employee_docs/'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='shift',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
