# Generated by Django 4.2.11 on 2025-11-03 12:04

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalarySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('present_days', models.IntegerField()),
                ('absent_days', models.IntegerField()),
                ('leave_days', models.IntegerField()),
                ('weekly_off_days', models.IntegerField()),
                ('total_work_hours', models.DurationField()),
                ('late_time', models.DurationField()),
                ('early_leave_time', models.DurationField()),
                ('over_time', models.DurationField()),
                ('final_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='attendance_app.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bank_transfer_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('yearly_bonus_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base salary এর কত % বোনাস হবে (যদি 0 থাকে তবে fixed bonus ব্যবহার হবে)', max_digits=5)),
                ('yearly_bonus_fixed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='এককালীন fixed bonus (percent 0 হলে)', max_digits=10)),
                ('bonus_payout_month', models.PositiveSmallIntegerField(default=12, help_text='কোন মাসে বোনাস দেওয়া হবে (1-12)')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance_app.company')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='attendance_app.employee')),
            ],
        ),
    ]
