# Generated by Django 4.2.11 on 2025-08-02 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalarySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('present_days', models.IntegerField()),
                ('absent_days', models.IntegerField()),
                ('leave_days', models.IntegerField()),
                ('weekly_off_days', models.IntegerField()),
                ('total_work_hours', models.DurationField()),
                ('late_time', models.DurationField()),
                ('early_leave_time', models.DurationField()),
                ('over_time', models.DurationField()),
                ('final_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bank_transfer_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='attendance_app.employee')),
            ],
        ),
    ]
