# Generated by Django 4.2.11 on 2025-08-13 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0004_employee_user'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarysummary',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='attendance_app.company'),
        ),
    ]
