# Generated by Django 4.2.11 on 2025-08-13 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0004_employee_user'),
        ('payroll', '0002_salarysummary_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalary',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance_app.company'),
        ),
    ]
