# Generated by Django 4.2.11 on 2025-08-16 11:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_employeesalary_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalary',
            name='bonus_payout_month',
            field=models.PositiveSmallIntegerField(default=12, help_text='কোন মাসে বোনাস দেওয়া হবে (1-12)'),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='yearly_bonus_fixed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='এককালীন fixed bonus (percent 0 হলে)', max_digits=10),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='yearly_bonus_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base salary এর কত % বোনাস হবে (যদি 0 থাকে তবে fixed bonus ব্যবহার হবে)', max_digits=5),
        ),
    ]
