# Generated by Django 4.2.11 on 2025-08-19 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_app', '0003_delete_subscription'),
        ('payment_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bkashpaymentexecute',
            name='subscription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bkash_payment', to='subscription_app.usersubscription'),
        ),
    ]
